resources:
  jobs:
    provisioned_throughput_deployment_job:
      name: provisioned_throughput_deployment
      tags:
        project_name: "arxiv-curator"

      environments:
        - environment_key: default
          spec:
            environment_version: "4"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: provisioned_throughput_deployment
          environment_key: default
          notebook_task:
            notebook_path: ../notebooks/1.2_provisioned_throughput_deployment.py
            base_parameters:
              env: ${bundle.target}
              git_sha: "${var.git_sha}"
              run_id: "{{job.run_id}}"
