name: CI

on:
  push:
    branches:
      - main
      - demo_submission
  workflow_dispatch:
      inputs:
        project:
          description: 'Which project to run?'
          required: true
          default: 'arxiv_curator'
          type: choice
          options:
            - arxiv_curator
            - nhtsa_defect_intel


jobs:
  pytest_and_checks:
    runs-on: ubuntu-latest
    env:
      # CHANGE THIS LINE ONLY to switch projects for automatic pushes
      ACTIVE_PROJECT: arxiv_curator
    defaults:
      run:
        working-directory: ${{ github.event.inputs.project || env.ACTIVE_PROJECT }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 #v5.4.1

      - name: Install the dependencies
        run: |
          uv sync --extra ci

      - name: Run pre-commit checks
        run: |
          uv run pre-commit run --all-files

      - name: Run pytest
        run: |
          uv run pytest

      - name: Build wheel
        run: |
          uv build
